### ISSUE TITLE
ParseServer.createLiveQueryServer is not a function

### ISSUE THREAD

**Issue by hasrants** [ParsePlatform/parse-server-example#129]
I am following the instructions to get parse server example running on Heroku. Regardless if I use the Button to install on Heroku or fork from GitHub. It fails to run with following error:

2016-03-23T19:11:42.158085+00:00 heroku[web.1]: State changed from crashed to starting
2016-03-23T19:11:45.125296+00:00 heroku[web.1]: Starting process with command `npm start`
2016-03-23T19:11:47.348553+00:00 app[web.1]: 
2016-03-23T19:11:47.348576+00:00 app[web.1]: > parse-server-example@1.4.0 start /app
2016-03-23T19:11:47.348577+00:00 app[web.1]: > node index.js
2016-03-23T19:11:47.348578+00:00 app[web.1]: 
2016-03-23T19:11:49.535595+00:00 app[web.1]: /app/node_modules/parse-server/lib/index.js:335
2016-03-23T19:11:49.535629+00:00 app[web.1]:             throw err;
2016-03-23T19:11:49.535638+00:00 app[web.1]:             ^
2016-03-23T19:11:49.535639+00:00 app[web.1]: 
2016-03-23T19:11:49.535646+00:00 app[web.1]: TypeError: ParseServer.createLiveQueryServer is not a function
2016-03-23T19:11:49.535647+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:55:13)
2016-03-23T19:11:49.535648+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-03-23T19:11:49.535648+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-03-23T19:11:49.535649+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-03-23T19:11:49.535650+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-03-23T19:11:49.535650+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)
2016-03-23T19:11:49.535651+00:00 app[web.1]:     at startup (node.js:142:18)
2016-03-23T19:11:49.535652+00:00 app[web.1]:     at node.js:939:3
2016-03-23T19:11:49.556131+00:00 app[web.1]: 
2016-03-23T19:11:49.572141+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-03-23T19:11:49.572335+00:00 app[web.1]: npm ERR! parse-server-example@1.4.0 start: `node index.js`
2016-03-23T19:11:49.569661+00:00 app[web.1]: npm ERR! Linux 3.13.0-79-generic
2016-03-23T19:11:49.570177+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-03-23T19:11:49.570486+00:00 app[web.1]: npm ERR! node v5.9.1
2016-03-23T19:11:49.571892+00:00 app[web.1]: npm ERR! npm  v3.7.3
2016-03-23T19:11:49.572721+00:00 app[web.1]: npm ERR! 
2016-03-23T19:11:49.572514+00:00 app[web.1]: npm ERR! Exit status 7

**Comment by drew-gross** [comment]
The issue is related to a change in Babel which caused parse-server version 2.2.1 to break. We'll be releasing a fix in 2.2.2 today, and in the meantime you can use version 2.2.0.
