### ISSUE TITLE
Error running on AWS Linux.

### ISSUE THREAD

**Issue by levisbotio** [ParsePlatform/parse-server-example#30]
I've installed Node.js, Python and MongoDB on my Amazon Linux, whem i'm trying to npm run start i'm getting this error.

```
 root@ip-127-0-0-1 [/var/www/parse-sample]# sudo npm run start

 parse-server-example@1.0.0 start /var/www/parse-sample
node index.js
/var/www/parse-sample/node_modules/parse-server/index.js:156
    request(options, (error, response, body) => {
                                              ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/parse-sample/index.js:5:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! Linux 4.1.13-19.31.amzn1.x86_64
npm ERR! argv "node" "/usr/bin/npm" "run" "start"
npm ERR! node v0.10.36
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! parse-server-example@1.0.0 start: `node index.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the parse-server-example@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-server-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-server-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parse-server-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/parse-sample/npm-debug.log
```

what seems to be the problem here? thanks!

**Comment by iulianvarzaru** [comment]
You have `node v0.10.36` but parse-server requires `"node": ">=4.1"`, that's why you get this error.

**Comment by gfosco** [comment]
Yep, not sure why NPM isn't enforcing the engines block of package.json, but this requires Node >=4.1.

**Comment by kukkadapukarhtik** [comment]
![screen shot 2016-03-24 at 10 18 00 am](https://cloud.githubusercontent.com/assets/12559796/14008661/c293f536-f1a9-11e5-9f7c-91dad0195338.png)
