### ISSUE TITLE
ParsePushAdapter.js throw __iteratorError

### ISSUE THREAD

**Issue by ruchanb** [ParsePlatform/parse-server-example#325]
**This is the log file**
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.11
3 info using node@v4.7.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart parse-server-example@1.4.0
6 info start parse-server-example@1.4.0
7 verbose unsafe-perm in lifecycle true
8 info parse-server-example@1.4.0 Failed to exec start script
9 verbose stack Error: parse-server-example@1.4.0 start: `node index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:854:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid parse-server-example@1.4.0
11 verbose cwd X:\Data\www\app_node\parse-server-punchorello
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.7.2
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error parse-server-example@1.4.0 start: `node index.js`
17 error Exit status 1
18 error Failed at the parse-server-example@1.4.0 start script 'node index.js'.
18 error This is most likely a problem with the parse-server-example package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs parse-server-example
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls parse-server-example
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

Steps to reproduce
1. git clone <latest parse-server-example>
2. npm install
3. change configuration to add android and ios configuration
4. npm start

Environment
1. node 4.7.2
2. windows 2008 server

Note: the issue only occurs with push config

**Comment by skrichten** [comment]
@ruchanb I have this issue right now, what was causing it for you?

**Comment by ruchanb** [comment]
I think it was with wrong configuration. Check for typos.
