### ISSUE TITLE
Recommend updates due to parse server and node.js versions changed

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-server-example#56]
I think parse-server now requires node.js 4.3 due to security issues in 4.1 and also a bump in the package.json for node 4.3 and parse server 2.0.8x

I'm having issues depolying to Heroku.. I updated locally on osx to node 4.3 updated the package json to point to node 4.3 and parser server 2.0.8.. 

Error I'm seeing from Heroku logs.

```
2016-02-12T20:20:09.998175+00:00 heroku[web.1]: State changed from crashed to starting
2016-02-12T20:20:11.428987+00:00 heroku[web.1]: Starting process with command `npm start`
2016-02-12T20:20:13.979841+00:00 app[web.1]: 
2016-02-12T20:20:13.979861+00:00 app[web.1]: 
2016-02-12T20:20:13.979861+00:00 app[web.1]: > node index.js
2016-02-12T20:20:13.979859+00:00 app[web.1]: > parse-server-example@1.0.0 start /app
2016-02-12T20:20:14.354049+00:00 app[web.1]: {"v":0,"level":30,"name":"newrelic","hostname":"xxxxxxxxx","pid":17,"time":"2016-02-12T20:20:14.352Z","msg":"Starting New Relic for Node.js connection process."}
2016-02-12T20:20:15.259983+00:00 app[web.1]: /app/node_modules/parse-server/src/Adapters/Files/S3Adapter.js:5
2016-02-12T20:20:15.259992+00:00 app[web.1]:     at exports.runInThisContext (vm.js:53:16)
2016-02-12T20:20:15.259988+00:00 app[web.1]: import * as AWS from 'aws-sdk';
2016-02-12T20:20:15.259992+00:00 app[web.1]:     at Module._compile (module.js:387:25)
2016-02-12T20:20:15.259991+00:00 app[web.1]: SyntaxError: Unexpected token import
2016-02-12T20:20:15.259993+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-02-12T20:20:15.281640+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-02-12T20:20:15.259989+00:00 app[web.1]: ^^^^^^
2016-02-12T20:20:15.280657+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-02-12T20:20:15.259995+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-02-12T20:20:15.281760+00:00 app[web.1]: npm ERR! parse-server-example@1.0.0 start: `node index.js`
2016-02-12T20:20:15.259996+00:00 app[web.1]:     at Function.cls_wrapMethod [as _load] (/app/node_modules/newrelic/lib/shimmer.js:230:38)
2016-02-12T20:20:15.280353+00:00 app[web.1]: npm ERR! Linux 3.13.0-71-generic
2016-02-12T20:20:15.280829+00:00 app[web.1]: npm ERR! node v5.6.0
2016-02-12T20:20:15.281859+00:00 app[web.1]: npm ERR! Exit status 1
2016-02-12T20:20:15.282086+00:00 app[web.1]: npm ERR! Failed at the parse-server-example@1.0.0 start script 'node index.js'.
2016-02-12T20:20:15.259990+00:00 app[web.1]: 
2016-02-12T20:20:15.281299+00:00 app[web.1]: npm ERR! npm  v3.6.0
2016-02-12T20:20:15.259999+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-02-12T20:20:15.281973+00:00 app[web.1]: npm ERR! 
2016-02-12T20:20:15.259998+00:00 app[web.1]:     at require (internal/module.js:16:19)
2016-02-12T20:20:15.282199+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2016-02-12T20:20:15.259997+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-02-12T20:20:15.282299+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the parse-server-example package,
2016-02-12T20:20:15.259994+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-02-12T20:20:15.273113+00:00 app[web.1]: 
2016-02-12T20:20:15.259999+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:7:17)
2016-02-12T20:20:15.282505+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-02-12T20:20:15.282607+00:00 app[web.1]: npm ERR!     node index.js
2016-02-12T20:20:15.282704+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-02-12T20:20:15.282407+00:00 app[web.1]: npm ERR! not with npm itself.
2016-02-12T20:20:15.282926+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-02-12T20:20:15.283117+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-02-12T20:20:15.286712+00:00 app[web.1]: 
2016-02-12T20:20:15.282810+00:00 app[web.1]: npm ERR!     npm bugs parse-server-example
2016-02-12T20:20:15.283012+00:00 app[web.1]: npm ERR!     npm owner ls parse-server-example
2016-02-12T20:20:15.286885+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-02-12T20:20:15.286980+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-02-12T20:20:16.022453+00:00 heroku[web.1]: State changed from starting to crashed
2016-02-12T20:20:15.989424+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by gateway** [comment]
resolved..

in my index.js I was trying to enable s3 adpator the wrong way..

from this 
var S3Adapter = require('parse-server/src/Adapters/Files/S3Adapter');
to this
var S3Adapter = require('parse-server').S3Adapter;
